[tool.poetry]
name = "tellmewhattodo"
version = "0.1.0"
description = "Simple app that checks for what to do and presents that in a website"
authors = ["Martin Morset <mmo@one.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.24.43"
pandas = "^1.4.3"
pydantic = "^1.9.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
boto3-stubs = {version = "1.24.43", extras = ["s3"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tools.black]
line-length = 100